### ISSUE TITLE
OpenMod Standalone crash on reloading

### ISSUE THREAD

**Issue by DiFFoZ** [openmod/openmod#304]
System.InvalidOperationException
  HResult=0x80131509
  Message=Коллекция была изменена; невозможно выполнить операцию перечисления. (Collection was modified; enumeration operation may not execute.)
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at OpenMod.Core.Persistence.YamlDataStore.OnFileChange(String filePath) in C:\Users\vamar\Source\Repos\OpenMod\framework\OpenMod.Core\Persistence\YamlDataStore.cs:line 158
   at OpenMod.Core.Persistence.YamlDataStore.<>c__DisplayClass12_0.<AddChangeWatcher>b__0(Object s, FileSystemEventArgs a) in C:\Users\vamar\Source\Repos\OpenMod\framework\OpenMod.Core\Persistence\YamlDataStore.cs:line 134
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by Trojaner** [comment]
Good catch
