### ISSUE TITLE
Cannot parse logging.yaml

### ISSUE THREAD

**Issue by DiFFoZ** [openmod/openmod#369]
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OpenMod.Core.Configuration.YamlConfigurationProviderEx.Load(Stream stream) in C:\Users\vamar\source\repos\openmod\framework\OpenMod.Core\Configuration\YamlConfigurationProviderEx.cs:line 51
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
SyntaxErrorException: (Line: 26, Col: 5, Idx: 1022) - (Line: 26, Col: 5, Idx: 1022): While scanning a simple key, could not find expected ':'.
```

**Comment by Trojaner** [comment]
The bug is still not fixed and happens in debug mode - maybe it happens on release too but silently (maybe this is why @Gegtor's logging config is not applied correctly?)

**Comment by Trojaner** [comment]
```yaml
path: "{{workingDirectory}}/logs/openmod.log" - no issue
path: "logs/openmod-{{date}}.log" - no issue
path: "{{workingDirectory}}/logs/openmod-{{date}}.log" - exception
path: "C:/Users/troja/source/repos/OpenMod/openmod/standalone/OpenMod.Standalone/bin/Debug/net461/openmod/logs/openmod-2021-02-08-02-01-34.log" - issue
path: "C:/Users/troja/source/repos/OpenMod/openmod/standalone/OpenMod.Standalone/bin/Debug/net461/openmod/logs/openmod.log" - no issue
path: "logs/openmod-2021-02-08-02-01-34.log" - no issue
```

**Comment by Trojaner** [comment]
YamlDotNet issue:
https://github.com/aaubry/YamlDotNet/issues/578
