### ISSUE TITLE
Auto restart lost connection to host bug

### ISSUE THREAD

**Issue by Anequit** [openmod/openmod#457]
Title says it, after an auto restart your server is left in a dead state.

**Comment by Anequit** [comment]
Forgot to add labels.

**Comment by Anequit** [comment]
Ugh I tried to add labels and completely forgot i couldn't so I closed it, but then I opened it, but then closed it on accident, so I'm leaving this open.

**Comment by Anequit** [comment]
Possible solution would be to reverse the two methods. Dispose, then start the process. https://github.com/openmod/openmod/blob/792494246a825ac0435e8ee643bd67f97a21abf5/framework/OpenMod.Core/Commands/OpenModCommands/CommandRestart.cs#L80

**Comment by DiFFoZ** [comment]
The problem is that Unturned\SteamNetworkingSocket doesn't close the connection properly, so the port and IP still will be blocked.

This problem also occurs when the RCON is enabled.
```
[20:39:21 ERR][OpenMod.Core.Rcon.Tcp.BaseTcpRconHost] Exception occured in RCON host task
System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at OpenMod.Core.Rcon.Tcp.BaseTcpRconHost`1.<>c__DisplayClass14_0.<<StartListeningAsync>b__1>d.MoveNext()
[20:39:21 INF][OpenMod.Core.Rcon.Tcp.BaseTcpRconHost] MinecraftRconHost stopped
```

**Comment by DiFFoZ** [comment]
The solution is to try to use this: https://stackoverflow.com/questions/1672062/how-to-close-a-tcp-connection-by-port
